[preset]
name = "All Jumper"
description = "Put here your description"

[functions]
#"jumper_swap_optimism" = "Jumper Swap Optimism"
"jumper_swap_unichain" = "Jumper Swap Unichain"

[repeat_actions]
"jumper_swap_unichain" = [1, 3]


[functions_params]
# POSSIBLE NETWORKS:

# ['Ethereum', 'Arbitrum', 'BSC', 'Polygon', 'Optimism', 'Base', 'Celo', 'opBNB', 'Scroll',
# 'Gnosis', 'Linea', 'Blast', 'Zksync', 'Ink', 'Mode', 'Unichain', 'Lisk', 'Soneium', 'Avalanche',
# 'PolygonZKEVM', 'Fantom', 'Moonriver', 'Moonbeam', 'Fuse', 'Boba', 'Metis', 'Aurora', 'Sei', 'ImmutableZKEVM',
# 'Sonic', 'Gravity', 'Taiko', 'Swellchain', 'Corn', 'Cronos', 'Abstract', 'Rootstock', 'Apechain', 'WorldChain', .
# 'XDC', 'Mantle', 'Superposition', 'BOB', 'Lens', 'Berachain', 'Kaia', 'HyperEVM']

# POSSIBLE SWAP MODES
# to_and_from - swaps back all available amount
# ['only_to', 'to_and_from']


### swap settings
[[functions_params.swap.unichain]]
from_token = "native"
to_token = "0x078D782b760474a361dDA0AF3839290b0EF57AD6"
swap_mode = "to_and_from"
amount = ["20", "30"]
#amount = [1.001 , 1.003]
slippage = 0.5 # %

#
#
[[functions_params.swap.optimism]]
from_token = "native"
to_token = "0x7F5c764cBc14f9669B88837ca1490cCa17c31607"
swap_mode = "only_to"
amount = [1.001 , 1.003]
slippage = 0.5 # %

#[[functions_params.swap.optimism]]
#from_token = "0x7F5c764cBc14f9669B88837ca1490cCa17c31607"
#to_token = "native"
#swap_mode = "only_to"
#amount = ["100", "100"]
#slippage = 0.1 # %

